# Generated by Django 2.2.3 on 2019-07-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
